version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: db_api
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolar_db